config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  get 'welcome/index'
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	
	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end
	
	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Hellz yeah, Extu! Your article was successfully saved!"
		else
			render 'new', notice: "Oh no, Extu! I was unable to save your post."
		end
	end

	def show
	end

	def edit
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Oshey! Your article was successfully saved!"
		else
			render 'edit'
		end
	end
	
	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :slug)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true,
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Oladimeji Tolu - UX Designer / Developer</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="main_navigation" class="clearfix">
<%= link_to "Oladimeji Tolu", root_path, class: "logo" %>
   <nav>
   	<%= link_to "Articles", posts_path %>
     <a href="#">Projects</a>
     <a href="#">Contact</a>
   </nav>
 </header>

<%= yield %>

<footer id="main_footer">
    <p class="copyright">&copy 2015 Oladimeji Tolu</p>
    <nav>
      <a href="http://twitter.com/extu_" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="http://instagram.com/extu" target="_blank"><i class="fa fa-instagram"></i></a>
      <a href="http://dribbble.com/extu" target="_blank"><i class="fa fa-dribbble"></i></a>
      <a href="http://github.com/andela-toladimeji" target="_blank"><i class="fa fa-github"></i></a>
      <a href="http://bitbucket.com/extu" target="_blank"><i class="fa fa-bitbucket"></i></a>
    </nav>
</footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'extublog';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<h2><%= pluralize(@post.errors.count, "error") %> Prevented this post from saving</h2>
	<ul>
      <% @post.error.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>

    <%= f.label :title %> <br>
    <%= f.text_field :title %>

    <br>
    <br>

    <%= f.label :content, "write your article here" %> <br>
    <%= f.text_area :content %>

    <br>
    <br>

     <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page_title"> Stuff I've Designed</h1>
<div id="post_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
		<div class="post">
			<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
			<h2><a href="#"><%= link_to post.title, post %></a></h2>
			<hr>
		</div>
	<% end %>
</div>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>Newpost</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_contents" class="skinny_wrapper wrapper_padding">
   <header>
     <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
     <h1><%= @post.title %></h1>
     <hr>
   </header>
   <div id="content">
     <%= markdown @post.content %>
   </div>

   <hr>

   <div id="share_box">
     <p>Share <%= @post.title %></p>
     <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @extu_ - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
      <i class="fa fa-twitter"></i></a>

      <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= @post.title %> by @extu_ - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
      <i class="fa fa-facebook"></i></a>

     <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= @post.title %> by @extu_ - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
      <i class="fa fa-google-plus"></i></a>
   </div>
   
   <hr>

   <%= render 'disqus' %>
   
 </div>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.slug %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @user.slug %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="col-1 about homepage_content">
    <h2>About</h2>
    <hr>
    <p>
      I am a user-interface designer &amp; front-end developer at <a href="#">Andela</a> who thrives on multi-disciplinary, creative exploration, and making the world a better place by creating usable products
    </p>
    <p>With every project I begin with an open, curious and empathetic mind in an attempt to understand the problem from every perspective. To further understand these design needs, and to ultimately find a fitting solution, I like to do a lot of learning by iteration and prototyping. This also allows me to validate and gather valuable feedback throughout the process, rather than just near the end, and also allows me to offer an intelligent rationale behind every decision.</p>
    <p>You can find me tweeting in 140 characters on <a href="#">Twitter</a>, swooshing some pixels on <a href="#">Dribbble</a>, and sharing some code on  <a href="#">Github</a> or <a href="#">Bitbucket</a>.
</p>
  </div>
  <div class="col-2 homepage_content">
    <h2>Stuff I've Designed</h2>
    <hr>

    <% @posts.each do |post| %>
    	<h3><a href="#"><%= link_to post.title, post %></a></h3>
    	<div class="date"><%= post.created_at.strftime("%A, %b %d") %></div>
    <% end %>
  </div>
  <div class="col-3 homepage_content">
    <h2>Stuff I've Designed</h2>
    <hr>
    <h3><a href="#">Fidelty Bank Redesign</a></h3>
    <div class="date">Friday, September 5th</div>
    <h3><a href="#">Tiketmobile</a></h3>
    <div class="date">Friday, September 5th</div>
    <h3><a href="#">Thaloot</a></h3>
    <div class="date">Friday, September 5th</div>
  </div>
  </div>
</div>